CREATE TABLE "Users" (
    "id"               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username"         varchar(100) UNIQUE NOT NULL,
    "email"            varchar(255) UNIQUE NOT NULL,
    "created_at"       timestamptz NOT NULL DEFAULT now(),
    "token_balance"    int         NOT NULL DEFAULT 0,
    "last_login"       timestamptz,
    "email_updated_at" timestamptz,
    "is_hidden"        bool        NOT NULL DEFAULT false,
    "banned_at"        timestamptz,
    "deleted_at"       timestamptz
);

CREATE TABLE "Accounts" (
    "user_id"             bigint       PRIMARY KEY REFERENCES "Users" ("id"),
    "provider"            varchar(25)  NOT NULL,
    "provider_user_id"    varchar(255) NOT NULL,
    "password_hash"       varchar(255),
    "password_updated_at" timestamptz,
    "created_at"          timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE "Countries" (
    "id"       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"     varchar(100),
    "code_iso" char(2) UNIQUE NOT NULL
);

CREATE TABLE "Profiles" (
    "user_id"    bigint PRIMARY KEY REFERENCES "Users" ("id"),
    "first_name" varchar(100),
    "last_name"  varchar(100),
    "bio"        text,
    "birth_date" date,
    "gender"     varchar(20),
    "country_id" bigint REFERENCES "Countries" ("id"),
    "updated_at" timestamptz
);

CREATE TABLE "Roles" (
    "id"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "UserRoles" (
    "user_id" bigint REFERENCES "Users" ("id"),
    "role_id" bigint REFERENCES "Roles" ("id"),
    PRIMARY KEY ("user_id", "role_id")
);

CREATE TABLE "UserLikes" (
    "user_id"       bigint REFERENCES "Users" ("id"),
    "liked_user_id" bigint REFERENCES "Users" ("id"),
    "liked_at"      timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("user_id", "liked_user_id")
);

CREATE TABLE "UserFollows" (
    "follower_id" bigint REFERENCES "Users" ("id"),
    "followed_id" bigint REFERENCES "Users" ("id"),
    "followed_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("follower_id", "followed_id")
);

CREATE TABLE "WritingStyles" (
    "id"       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"     varchar(50) UNIQUE NOT NULL,
    "rules"    text,
    "settings" jsonb
);

COMMENT ON COLUMN "WritingStyles"."settings" IS 'e.g. {"max_visible_paragraphs": 3, "can_see_own": true}';

CREATE TABLE "Genres" (
    "id"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "Stories" (
    "id"               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title"            varchar(255) NOT NULL,
    "slug"             varchar(100) UNIQUE NOT NULL,
    "description"      text         NOT NULL,
    "author_id"        bigint       NOT NULL REFERENCES "Users" ("id"),
    "writing_style_id" bigint       REFERENCES "WritingStyles" ("id"),
    "language_code"    char(2)      NOT NULL DEFAULT 'en',
    "status"           varchar(20),
    "price_cents"      int,
    "continuation_of"  bigint       REFERENCES "Stories" ("id"),
    "created_at"       timestamptz  NOT NULL DEFAULT now(),
    "updated_at"       timestamptz,
    "published_at"     timestamptz,
    "banned_at"        timestamptz,
    "deleted_at"       timestamptz
);

CREATE TABLE "StoryGenres" (
    "story_id" bigint REFERENCES "Stories" ("id"),
    "genre_id" bigint REFERENCES "Genres" ("id"),
    PRIMARY KEY ("story_id", "genre_id")
);

CREATE TABLE "StoryLikes" (
    "user_id"    bigint REFERENCES "Users" ("id"),
    "story_id"   bigint REFERENCES "Stories" ("id"),
    "created_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("user_id", "story_id")
);

CREATE TABLE "Paragraphs" (
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "story_id"   bigint      NOT NULL REFERENCES "Stories" ("id"),
    "author_id"  bigint      REFERENCES "Users" ("id"),
    "position"   int         NOT NULL,
    "content"    text        NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz,
    "banned_at"  timestamptz,
    "deleted_at" timestamptz
);

CREATE TABLE "Characters" (
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "creator_id"  bigint       REFERENCES "Users" ("id"),
    "name"        varchar(100) NOT NULL,
    "race"        varchar(50),
    "gender"      varchar(20),
    "age"         int,
    "skills"      jsonb,
    "backstory"   text,
    "appearance"  text,
    "description" text,
    "image_url"   varchar(255),
    "created_at"  timestamptz  NOT NULL DEFAULT now(),
    "updated_at"  timestamptz,
    "banned_at"   timestamptz,
    "deleted_at"  timestamptz
);

CREATE TABLE "CharacterRelations" (
    "character_id"         bigint REFERENCES "Characters" ("id"),
    "related_character_id" bigint REFERENCES "Characters" ("id"),
    "relation_type"        varchar(100) NOT NULL,
    PRIMARY KEY ("character_id", "related_character_id")
);

CREATE TABLE "CharacterStory" (
    "character_id" bigint REFERENCES "Characters" ("id"),
    "story_id"     bigint REFERENCES "Stories" ("id"),
    PRIMARY KEY ("character_id", "story_id")
);

CREATE TABLE "Transactions" (
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"      bigint      NOT NULL REFERENCES "Users" ("id"),
    "type"         varchar(50) NOT NULL,
    "status"       varchar(20) NOT NULL,
    "amount_cents" int         NOT NULL,
    "created_at"   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "TokenEvents" (
    "id"             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"        bigint      REFERENCES "Users" ("id"),
    "transaction_id" bigint      REFERENCES "Transactions" ("id"),
    "delta_tokens"   int         NOT NULL,
    "reason"         varchar(50),
    "created_at"     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "Tips" (
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"      bigint REFERENCES "Users" ("id"),
    "story_id"     bigint REFERENCES "Stories" ("id"),
    "amount_cents" int,
    "message"      text,
    "tipped_at"    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "StoryUnlocks" (
    "user_id"     bigint REFERENCES "Users" ("id"),
    "story_id"    bigint REFERENCES "Stories" ("id"),
    "unlocked_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("user_id", "story_id")
);

CREATE TABLE "ParagraphUnlocks" (
    "user_id"      bigint REFERENCES "Users" ("id"),
    "paragraph_id" bigint REFERENCES "Paragraphs" ("id"),
    "unlocked_at"  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("user_id", "paragraph_id")
);

CREATE TABLE "Payouts" (
    "id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"      bigint REFERENCES "Users" ("id"),
    "amount_cents" int,
    "status"       varchar(20),
    "requested_at" timestamptz NOT NULL DEFAULT now(),
    "paid_at"      timestamptz
);

-- Indexes on FK columns (PostgreSQL does not create these automatically)

CREATE INDEX ON "Profiles" ("country_id");
CREATE INDEX ON "UserRoles" ("user_id");
CREATE INDEX ON "UserRoles" ("role_id");
CREATE INDEX ON "UserLikes" ("liked_user_id");
CREATE INDEX ON "UserFollows" ("followed_id");
CREATE INDEX ON "Stories" ("author_id");
CREATE INDEX ON "Stories" ("writing_style_id");
CREATE INDEX ON "Stories" ("continuation_of");
CREATE INDEX ON "Paragraphs" ("story_id", "position");
CREATE INDEX ON "Paragraphs" ("author_id");
CREATE INDEX ON "Characters" ("creator_id");
CREATE INDEX ON "Accounts" ("provider", "provider_user_id");
CREATE INDEX ON "TokenEvents" ("user_id");
CREATE INDEX ON "TokenEvents" ("transaction_id");
CREATE INDEX ON "Tips" ("user_id");
CREATE INDEX ON "Tips" ("story_id");
CREATE INDEX ON "StoryUnlocks" ("user_id");
CREATE INDEX ON "StoryUnlocks" ("story_id");
CREATE INDEX ON "ParagraphUnlocks" ("user_id");
CREATE INDEX ON "ParagraphUnlocks" ("paragraph_id");
CREATE INDEX ON "Payouts" ("user_id");
